### ISSUE TITLE
A 401 error

### ISSUE THREAD

**Issue by RiteshS1** [shubhagarwal1/Git-Stats#2]
Upon submitting a new username it gives a 401 error!
![Screenshot 2024-11-15 214802](https://github.com/user-attachments/assets/63e88045-c8ce-400d-8093-b3f77029681b)

**Comment by shubhagarwal1** [comment]
Hey @RiteshS1, yes that is because i have not uploaded the git token in the prod, i will make that available soon.
Thank you for raising the issue.
